ALTER TABLE students
    ADD COLUMN school_type ENUM('ELEMENTARY', 'MIDDLE', 'HIGH', 'ETC'),
    ADD COLUMN grade_level ENUM('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', 'ETC'),
    ADD COLUMN department_type ENUM('LIBERAL_ARTS','NATURAL_SCIENCES', 'PHYSICAL_EDUCATION', 'ETC'),
    ADD COLUMN school_name VARCHAR(255),
    ADD COLUMN memo VARCHAR(255);