name: Deploy Spring Boot Application to AWS EC2

on:
  push:
    branches: [ main ] # main branch로 push 될 때 실행됩니다.

# 해당 yml 내에서 사용할 key - value
env:
  BUCKET_NAME: edubill-prd
  
# workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있습니다.
jobs:
  build:
    name: CD
    # 해당 jobs에서 아래의 steps들이 어떠한 환경에서 실행될 것인지를 지정합니다.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
  
      - name: Build with Gradle
        run: ./gradlew build
          
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Upload to S3 stroage
      - name: Upload to S3
        run: aws s3 cp ./$GITHUB_SHA.zip s3://$BUCKET_NAME/deploy/$GITHUB_SHA.zip --region ap-northeast-2

      # CodeDeploy에게 배포 명령을 내린다.
      - name: Code Deploy
        run: >
         aws deploy create-deployment --application-name edubill-prd
         --deployment-config-name CodeDeployDefault.AllAtOnce
         --deployment-group-name edubill-target-prd
         --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=deploy/$GITHUB_SHA.zip
